import type { Metadata } from "next";
import { Azeret_Mono, Lora, Gupter } from "next/font/google";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { AdminAuthProvider } from "@/components/admin/admin-auth-provider";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";

// Azeret Mono for headings/display text
const azeretMono = Azeret_Mono({
  variable: "--font-azeret-mono",
  subsets: ["latin"],
  display: "swap",
});

// Liter is not on Google Fonts - using Lora as a refined serif alternative
// that captures the editorial, museum-catalog feel
const liter = Lora({
  variable: "--font-liter",
  subsets: ["latin"],
  display: "swap",
});

// Gupter Bold for the Museum Moments logo
const gupter = Gupter({
  weight: "700",
  variable: "--font-gupter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_SITE_URL ||
      (process.env.VERCEL_PROJECT_PRODUCTION_URL
        ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`
        : "https://museum-moments.com")
  ),
  title: {
    default: "Museum Moments",
    template: "%s — Museum Moments",
  },
  description:
    "Museum Moments is a curated exhibition of design inspiration. The things that inspire and are beautiful, whether generated by AI or shaped by human hands.",
  keywords: [
    "design",
    "inspiration",
    "archive",
    "curation",
    "web design",
    "typography",
    "branding",
    "AI",
    "artificial intelligence",
    "exhibition",
    "museum",
    "design curation",
  ],
  authors: [{ name: "Juan Gabriel Delgado" }],
  creator: "Juan Gabriel Delgado",
  icons: {
    icon: "/icon.svg",
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    siteName: "Museum Moments",
    title: "Museum Moments",
    description:
      "Museum Moments is a curated exhibition of design inspiration. The things that inspire and are beautiful, whether generated by AI or shaped by human hands.",
  },
  twitter: {
    card: "summary_large_image",
    title: "Museum Moments",
    description:
      "Museum Moments is a curated exhibition of design inspiration. The things that inspire and are beautiful, whether generated by AI or shaped by human hands.",
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify([
              {
                "@context": "https://schema.org",
                "@type": "WebSite",
                name: "Museum Moments",
                url: "https://museum-moments.com",
                description:
                  "A curated exhibition of design inspiration to build the beautiful in the age of AI.",
              },
              {
                "@context": "https://schema.org",
                "@type": "Organization",
                name: "Museum Moments",
                url: "https://museum-moments.com",
                founder: {
                  "@type": "Person",
                  name: "Juan Gabriel Delgado",
                  url: "https://juangabriel.xyz",
                },
                sameAs: [
                  "https://x.com/juangadm_",
                  "https://www.linkedin.com/in/juangadm/",
                  "https://www.threads.com/@juangadm",
                ],
              },
            ]),
          }}
        />
      </head>
      <body className={`${azeretMono.variable} ${liter.variable} ${gupter.variable} antialiased`}>
        <AdminAuthProvider>
          <div className="min-h-screen flex flex-col" style={{ paddingLeft: 'env(safe-area-inset-left)', paddingRight: 'env(safe-area-inset-right)', paddingBottom: 'env(safe-area-inset-bottom)' }}>
            <Header />
            <main className="flex-1 -mt-[6px]">{children}</main>
            <Footer />
          </div>
        </AdminAuthProvider>
        <Analytics />
      </body>
    </html>
  );
}
